name: CI Pipeline - Backend

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Run Go Tests
        run: |
          cd server
          go test -v ./...
