name: CI Pipeline - Frontend

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Run frontend tests
        run: |
          cd client
          npm run test

      - name: Run Semgrep SAST on frontend
        run: |
          pip install semgrep
          semgrep --config=./client/semgrep.yml ./client/src/

      - name: Verify frontend code formatting
        run: |
          cd client
          npx prettier --check .

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Image Tags
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=ghcr.io/${REPO_OWNER}/todo-app/client:${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_TAG_LATEST=ghcr.io/${REPO_OWNER}/todo-app/client:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST -f client/Dockerfile client

      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: "${{ env.IMAGE_TAG_LATEST }}"
          fail-build: false

      - uses: anchore/sbom-action@v0
        with:
          image: "${{ env.IMAGE_TAG_LATEST }}"
          path: .
          format: spdx-json
          upload-artifact: true
          upload-release-assets: true

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_TAG
          docker push $IMAGE_TAG_LATEST
